@baseUrl = http://localhost:5080

GET {{baseUrl}}/api/v1/health
Accept: application/json

###

GET {{baseUrl}}/api/v1/app/bootstrap
Accept: application/json

###

GET {{baseUrl}}/openapi/v1.json
Accept: application/json
